### ISSUE TITLE
Date/time helpers tests are failing when run in different timezone

### ISSUE THREAD

**Issue by AlexeyDemidov** [gocardless/gocardless-legacy-ruby#52]
I have just noticed that rspec tests for date/time helpers are failing on my machine, possibly due to different timezone (UTC+4).

```
  1) GoCardless::Utils date and time helpers .iso_format_time should work with a Time object
     Failure/Error: d.should == "2012-01-01T00:00:00Z"
       expected: "2012-01-01T00:00:00Z"
            got: "2011-12-31T20:00:00Z" (using ==)
     # ./spec/utils_spec.rb:209:in `block (4 levels) in <top (required)>'

  2) GoCardless::Utils date and time helpers .stringify_times stringifies time objects
     Failure/Error: d.should == "2012-01-01T00:00:00Z"
       expected: "2012-01-01T00:00:00Z"
            got: "2011-12-31T20:00:00Z" (using ==)
     # ./spec/utils_spec.rb:231:in `block (4 levels) in <top (required)>'

  3) GoCardless::Utils date and time helpers .stringify_times stringifies time values in hashes
     Failure/Error: d.should == { :t => "2012-01-01T00:00:00Z" }
       expected: {:t=>"2012-01-01T00:00:00Z"}
            got: {:t=>"2011-12-31T20:00:00Z"} (using ==)
       Diff:
       @@ -1,2 +1,2 @@
       -:t => "2012-01-01T00:00:00Z"
       +:t => "2011-12-31T20:00:00Z"

     # ./spec/utils_spec.rb:236:in `block (4 levels) in <top (required)>'

  4) GoCardless::Utils date and time helpers .stringify_times stringifies time values in arrays
     Failure/Error: d.should == ["2012-01-01T00:00:00Z"]
       expected: ["2012-01-01T00:00:00Z"]
            got: ["2011-12-31T20:00:00Z"] (using ==)
     # ./spec/utils_spec.rb:241:in `block (4 levels) in <top (required)>'
```
